<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>API маршрутизация</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>API маршрутизация определяет маршруты запроса для предоставления доступа к функционалу компонентов (модулей, расширений модулей) веб-приложения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список маршрутов</a></li>
        <li><a href="<?= $url('form') ?>">Форма редактирования маршрута</a></li>
    </ul>
</article>